// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The catalog service2 currently serves
    #
    # + return - The current page of the catalog
    resource function get catalog(int 'limit = 20, int offset = 0) returns CatalogPage {
        Record[] catalog = currentCatalog();
        CatalogPage page = paginate(catalog, 'limit, offset);
        log:printInfo("catalog request handled", recordsReturned = page.data.length(), totalRecords = page.count, mode = getCatalogMode());
        return page;
    }

    # Switch service2 between full mode and empty mode
    #
    # + return - The mode now in effect
    resource function put catalog\-mode(@http:Payload CatalogMode payload) returns CatalogMode {
        "full"|"empty" mode = setCatalogMode(payload.mode);
        return {mode: mode};
    }
}

public type CatalogMode record {|
    # full serves the fixed 10-record catalog; empty serves no records
    "full"|"empty" mode;
|};

public type CatalogPage record {|
    # total records in the current catalog
    int count;
    # relative URI of the next page
    string? next = ();
    # relative URI of the previous page
    string? previous = ();
    Record[] data;
|};

public type Record record {|
    # record identifier
    int id;
    # record name
    string name;
    # record score
    int score;
|};
